### ISSUE TITLE
Iteration 4 tests are only passed when iteration 5 is complete

### ISSUE THREAD

**Issue by carlarsmendes** [ironhack-labs/lab-dom-ironhack-cart#2250]
While trying to solve the #4 iteration, I noticed the tests were not passing even though everything was performing as expected.
Only when I solved the #5 iteration, everything was green at once. 
I then tested with the solution in webdev-labs-solutions and the same behavior was showing.
Looks like there is some dependency between those two tests.
Until it's fixed, I'll let my students know it's a bug :)
Below some screenshots of the errors.
Thanks for your help!
![image](https://user-images.githubusercontent.com/38359702/141306056-455b783f-af11-4a02-b6d3-ec245b1af5a5.png)
![image](https://user-images.githubusercontent.com/38359702/141306278-f41e4005-3d15-476d-96ae-df5517efcc0d.png)

**Comment by rjkerrison** [comment]
Just adding more detail that we found in class today. The tests fail because the removal tests have a `beforeEach` which remove all products, and then each iteration attempts to create a product before with which to test the removal.

A solution could be to test removal functionality against existing products from page load.
